### PR TITLE
Fix output format for txids in `sendprogress` command

### PR DESCRIPTION
**Pull request by dorianvp**

### CODE REVIEW

**Comment by dorianvp** [comment]
Running a CLT...

**Comment by dorianvp** [comment]
```
------------
     Summary [ 794.964s] 336 tests run: 336 passed (112 slow), 30 skipped


git show -s
commit 725a59c85396bf8d34dce78d9324b3dd7bd81edc (HEAD, dorian/sendprogress-out-format)
Author: dorianvp <dariovp01@gmail.com>
Date:   Thu Nov 21 23:31:42 2024 -0300

    fix: use json format for tx ids


```

**Review by zancas — APPROVED** [review]

**Comment by zancas** [comment]
I"m running a CLT, in the meantime let's ship this to @juanky201271 for a manual test?

**Comment by juanky201271** [comment]
Thanks @dorianvp I believe that this PR fixed this issue: https://github.com/zingolabs/zingolib/issues/1469

**Pull request merged**
