### PR TITLE
add donation address to zingoconfig

### PR DESCRIPTION
**Pull request by zancas**

### CODE REVIEW

**Review by Oscar-Pepper — COMMENTED** [review]
I'm wondering if we merge this without it being used to add a command to send to this address it may just get lost in the code? Should this be the start of a PR that implements such a command?

**Comment by zancas** [comment]
It seems like @juanky201271 was able to access this address?

Any reason to not merge?

**Comment by juanky201271** [comment]
> It seems like @juanky201271 was able to access this address?
> 
> Any reason to not merge?

I wasn't actually, I copied here: https://github.com/zingolabs/zingo-mobile/blob/6a7643100973dfe95ad1bfe7913fb2909487cd67/app/utils/Utils.ts#L99 waiting for accessing to this constant in zingolib, but I guess I need a command or something to get this UA from zingolib...

**Review by fluidvanadium — APPROVED** [review]
utACK

**Pull request merged**
