### PR TITLE
Hotfix transparent viewkey missing

### PR DESCRIPTION
**Pull request by fluidvanadium**
includes test that covers

### CODE REVIEW

**Comment by fluidvanadium** [comment]
ignore the clippy here. its updated in dev but not worth hotfixing

**Review by juanky201271 — COMMENTED** [review]
My concern about this is:
- A user can restore from vk, and after that when the user wants to check the vk, the App shows up an error message?
- `Restore from ufvk` & `exportufvk` would have to be synchronize, right? both with an error message or not, something coherent.

**Comment by fluidvanadium** [comment]
right o. the new version should export the transparentless viewkey

**Comment by fluidvanadium** [comment]
addresses the panic on line 179 of unified.rs

**Review by Oscar-Pepper — DISMISSED** [review]
great job

**Review by Oscar-Pepper — APPROVED** [review]

**Comment by juanky201271** [comment]
> right o. the new version should export the transparentless viewkey

Thanks, I appreciated that.

**Pull request merged**
