### PR TITLE
add test sync baseline

### PR DESCRIPTION
**Pull request by Oscar-Pepper**

### CODE REVIEW

**Review by fluidvanadium — COMMENTED** [review]
how do i run this new test?

**Comment by Oscar-Pepper** [comment]
> how do i run this new test?

Cargo test time_to_sync_baseline --release

Or even better try nextest
I think to install is
Cargo install cargo-nextest --locked
Then run
Cargo nextest run tome_to_sync_baseline --release

**Comment by fluidvanadium** [comment]
heres the error i got
```
cargo test time_to_sync_baseline --release
   Compiling zingo-cli v0.2.0 (/home/sava/ZINGO/tzingo-lib/zingocli)
    Finished release [optimized] target(s) in 2m 31s
     Running unittests src/lib.rs (target/release/deps/zingo_cli-baf3f4f5ff818773)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/release/deps/zingo_cli-e799aa6a8830a440)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration_tests.rs (target/release/deps/integration_tests-af6dd5ef73bea213)

running 1 test
test time_to_sync_baseline has been running for over 60 seconds
test time_to_sync_baseline ... FAILED

failures:

---- time_to_sync_baseline stdout ----
[zingocli/tests/utils/mod.rs:20] tips[0]["height"].clone() = Number(
    Number {
        category: 1,
        exponent: 0,
        mantissa: 1,
    },
)
[zingocli/tests/utils/mod.rs:20] tips[0]["height"].clone() = Number(
    Number {
        category: 1,
        exponent: 0,
        mantissa: 640,
    },
)
**Batch** Current:    0 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    0 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    0 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    0 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    1 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    1 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    1 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    1 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    2 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    2 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    2 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    2 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    2 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    3 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:    0, Total:  100,
**Batch** Current:    3 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    3 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    3 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    3 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:    0, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    4 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    5 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    5 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   98, Total:  100,
**Batch** Current:    5 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    5 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    5 Total:    7
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:   99, Total:  100,
**Batch** Current:    6 Total:    7
   Blocks Loaded:   39 TrialDecrypted:   39, Witnesses Updated:   37, Total:   39,
**Batch** Current:    6 Total:    7
   Blocks Loaded:   39 TrialDecrypted:   39, Witnesses Updated:   37, Total:   39,
**Batch** Current:    6 Total:    7
   Blocks Loaded:   39 TrialDecrypted:   39, Witnesses Updated:   38, Total:   39,
[zingocli/tests/integration_tests.rs:2902] sync_duration_faucet.as_millis() = 150320
**Batch** Current:    3 Total:    8
   Blocks Loaded:  100 TrialDecrypted:  100, Witnesses Updated:    0, Total:  100,
[zingocli/tests/integration_tests.rs:2908] sync_duration_recipient.as_millis() = 5852
thread 'time_to_sync_baseline' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `2`', zingocli/tests/integration_tests.rs:2910:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    time_to_sync_baseline

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 39 filtered out; finished in 1429.56s

error: test failed, to rerun pass `-p zingo-cli --test integration_tests`
```

**Comment by zancas** [comment]
I'm going to update the framework to use a cached blockchain that should fix this error.

**Pull request closed without merging**
