### PR TITLE
Update zcash client backend

### PR DESCRIPTION
**Pull request by zancas**

### CODE REVIEW

**Comment by zancas** [comment]
After the first 3 commits I ran the following:

```
cargo check
    Checking zingo-memo v0.1.0 (/home/nattyb/src/zingolabs/zingolibs/fix_shard_init/zingo-memo)
warning: Git command output: Output { status: ExitStatus(unix_wait_status(0)), stdout: "mob-release-1.2.5_126-293-gfe4df843\n", stderr: "" }
error[E0277]: the trait bound `zcash_primitives::consensus::MainNetwork: zcash_primitives::consensus::Parameters` is not satisfied
   --> zingo-memo/src/lib.rs:61:40
    |
61  |     let mainnet_encoded_ua = ua.encode(&zcash_primitives::consensus::MAIN_NETWORK);
    |                                 ------ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `zcash_primitives::consensus::Parameters` is not implemented for `zcash_primitives::consensus::MainNetwork`
    |                                 |
    |                                 required by a bound introduced by this call
    |
    = help: the following other types implement trait `zcash_primitives::consensus::Parameters`:
              zcash_primitives::consensus::MainNetwork
              zcash_primitives::consensus::TestNetwork
              zcash_primitives::consensus::Network
note: required by a bound in `UnifiedAddress::encode`
   --> /home/nattyb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zcash_client_backend-0.10.0-rc.2/src/address.rs:169:22
    |
169 |     pub fn encode<P: consensus::Parameters>(&self, params: &P) -> String {
    |                      ^^^^^^^^^^^^^^^^^^^^^ required by this bound in `UnifiedAddress::encode`

error[E0277]: the trait bound `UnifiedAddress: From<zcash_address::unified::Address>` is not satisfied
  --> zingo-memo/src/lib.rs:91:30
   |
91 |     UnifiedAddress::try_from(address).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))
   |     ------------------------ ^^^^^^^ the trait `From<zcash_address::unified::Address>` is not implemented for `UnifiedAddress`
   |     |
   |     required by a bound introduced by this call
   |
   = help: the trait `TryFrom<zcash_address::kind::unified::address::Address>` is implemented for `UnifiedAddress`
   = note: required for `zcash_address::unified::Address` to implement `Into<UnifiedAddress>`
   = note: required for `UnifiedAddress` to implement `TryFrom<zcash_address::unified::Address>`

error[E0277]: the trait bound `UnifiedAddress: From<zcash_address::unified::Address>` is not satisfied
  --> zingo-memo/src/lib.rs:91:5
   |
91 |     UnifiedAddress::try_from(address).map_err(|e| io::Error::new(io::ErrorKind::InvalidData, e))
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<zcash_address::unified::Address>` is not implemented for `UnifiedAddress`
   |
   = help: the trait `TryFrom<zcash_address::kind::unified::address::Address>` is implemented for `UnifiedAddress`
   = note: required for `zcash_address::unified::Address` to implement `Into<UnifiedAddress>`
   = note: required for `UnifiedAddress` to implement `TryFrom<zcash_address::unified::Address>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `zingo-memo` (lib) due to 3 previous errors
```

Perhaps the missing trait exists in the latest version of `zcash_address`?  I changing Cargo.toml to point at `zcash_address = "0.3", to see what happens.

**Comment by zancas** [comment]
OK!   Updating `zcash_address = "0.3"` seems to have provided the missing trait!

**Comment by zancas** [comment]
After updating to `incrementalmerkletree = { version = "0.5", features = ["test-dependencies"] }`:

```
error[E0308]: mismatched types
    --> zingolib/src/wallet/transactions.rs:637:25
     |
636  |                     .remove_mark(
     |                      ----------- arguments to this method are incorrect
637  |                         *nd.witnessed_position(),
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^ expected `incrementalmerkletree::Position`, found `Position`
     |
     = note: `Position` and `incrementalmerkletree::Position` have similar names, but are actually distinct types
note: `Position` is defined in crate `incrementalmerkletree`
    --> /home/nattyb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/incrementalmerkletree-0.5.0/src/lib.rs:142:1
     |
142  | pub struct Position(u64);
     | ^^^^^^^^^^^^^^^^^^^
note: `incrementalmerkletree::Position` is defined in crate `incrementalmerkletree`
    --> /home/nattyb/.cargo/git/checkouts/incrementalmerkletree-cc507a7e80715a08/bae25ad/incrementalmerkletree/src/lib.rs:138:1
     |
138  | pub struct Position(u64);
     | ^^^^^^^^^^^^^^^^^^^
     = note: perhaps two different versions of crate `incrementalmerkletree` are being used?
```

I guess this is because `shardtree` is "behind" so I update it to:

`shardtree = "0.1"`.

**Comment by zancas** [comment]
After the shardtree update:
```
error[E0308]: mismatched types
   --> zingolib/src/wallet/traits.rs:930:71
    |
930 |             .find(|unified_address| unified_address.orchard() == Some(receiver))
    |                                                                  ---- ^^^^^^^^ expected `orchard::address::Address`, found `orchard::Address`
    |                                                                  |
    |                                                                  arguments to this enum variant are incorrect
    |
    = note: `orchard::Address` and `orchard::address::Address` have similar names, but are actually distinct types
note: `orchard::Address` is defined in crate `orchard`
   --> /home/nattyb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/orchard-0.5.0/src/address.rs:19:1
    |
19  | pub struct Address {
    | ^^^^^^^^^^^^^^^^^^
note: `orchard::address::Address` is defined in crate `orchard`
   --> /home/nattyb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/orchard-0.6.0/src/address.rs:19:1
    |
19  | pub struct Address {
    | ^^^^^^^^^^^^^^^^^^
    = note: perhaps two different versions of crate `orchard` are being used?
    ```
    
So update orchard to:

`orchard = "0.6"`

**Comment by zancas** [comment]
In order to unify the dependencies such that `zcash_client_sqlite` no longer pulls in an obsolete `shardtree@0.0.0` updated `zcash_client_sqlite` to latest `rc`.

In order to pick up new interfaces to `zcash_proofs` updated `zcash_proofs` to latest `rc`.

**Comment by zancas** [comment]
`read_shard` and `write_shard` are now in the `zcash_client_backend` with feature "unstable-serialization".

With that functionality moved to `zcash_client_backend` we remove the dependency on:
`zcash_sqlite_client`.

**Review by AloeareV — APPROVED** [review]
Looks great!

**Comment by zancas** [comment]
So now I need a new approval @juanky201271 !

**Review by juanky201271 — APPROVED** [review]
@AloeareV approved this, and I do as well...

**Pull request merged**
