### PR TITLE
ring 0.17.X upgrade

### PR DESCRIPTION
**Pull request by juanky201271**
In order to build `Zingo-pc` for `windows arm64` I need to upgrade to `ring 0.17.x`

I need to upgrade `BIP0039` from `0.10.1` to `0.11.0` or `0.12.0` in `zcash_primitives` (https://github.com/zingolabs/librustzcash.git?tag=always_require_change#ae0d477a).

I don't have a clue if this can be a problem in `zingolib`.

@idky137 Can you help me with that, I hear you have a lot of experience with dependencies...

### CODE REVIEW

**Comment by zancas** [comment]
Hi @AloeareV is this review ready?   It is marked draft.

**Comment by AloeareV** [comment]
> Hi @AloeareV is this review ready? It is marked draft.

Yes, this is review ready! It currently depends on a librustzcash version by commit hash instead of by tag, https://github.com/zingolabs/librustzcash/pull/25 is the PR with the changed librustzcash.

**Comment by zancas** [comment]
So maybe we should put this behind the LRZ upgrade?

**Comment by zancas** [comment]
Let's deprioritze this behind the LRZ update.

**Comment by AloeareV** [comment]
> Let's deprioritze this behind the LRZ update.

I don't know what you mean. The LRZ update is functional.

**Comment by zancas** [comment]
> > Let's deprioritze this behind the LRZ update.
> 
> I don't know what you mean. The LRZ update is functional.

If this PR is not necessary to support ZIP320 in mobile, then let's delay work on it.

**Comment by juanky201271** [comment]
closing in favor of: #1457

**Pull request closed without merging**
