### PR TITLE
Return struct from do_balance and do_send_progress instead of JSON

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by AArnott** [comment]
@juanky201271 to take a particular look at this.

**Comment by juanky201271** [comment]
It seems perfect

> @juanky201271 to take a particular look at this.

I tested `balance` & `sendprogress` from your branch `nerdcash:stronglyTypedSyncResult2` and the result is perfectly aligned with what is expecting `zingo-mobile`. Thanks.

I'm not the person for reviewing the `rust` stuff... sorry.

**Review by fluidvanadium — APPROVED** [review]
another great step toward saner data handling

**Comment by AArnott** [comment]
Ah, I authored that commit on my ubuntu VM which doesn't sign. I've pushed a fix.

**Pull request merged**
