### PR TITLE
Nu6

### PR DESCRIPTION
**Pull request by fluidvanadium**
for code comparison

### CODE REVIEW

**Comment by AloeareV** [comment]
Me and @fluidvanadium have been having difficultly getting this to work with testnet, but this turns on NU6 for all our orchard-enabled regtest and darkside tests, and they function!

**Review by pacu — APPROVED** [review]

**Comment by fluidvanadium** [comment]
nice job @AloeareV ! 

im rolling out better test automation for this

**Comment by fluidvanadium** [comment]
manual testnet success

**Comment by fluidvanadium** [comment]
actually, now im getting the following issue:

`
(test) Block:3069165 (type 'help') >> quicksend tmD7TWQEK9LX6kBXtV1qUanqQVWNCNhJRMz 10000
{
  "error": "send Broadcast(Broadcast(\"Error: SendResponse { error_code: -26, error_message: \\\"16: bad-txns-orchard-unknown-anchor\\\" }\"))"
}
`

**Comment by fluidvanadium** [comment]
but it might be due to user error. i may have corrupted the wallet file


> actually, now im getting the following issue:
> 
> `(test) Block:3069165 (type 'help') >> quicksend tmD7TWQEK9LX6kBXtV1qUanqQVWNCNhJRMz 10000 { "error": "send Broadcast(Broadcast(\"Error: SendResponse { error_code: -26, error_message: \\\"16: bad-txns-orchard-unknown-anchor\\\" }\"))" }`

**Comment by fluidvanadium** [comment]
> but it might be due to user error. i may have corrupted the wallet file
> 
> > actually, now im getting the following issue:
> > `(test) Block:3069165 (type 'help') >> quicksend tmD7TWQEK9LX6kBXtV1qUanqQVWNCNhJRMz 10000 { "error": "send Broadcast(Broadcast(\"Error: SendResponse { error_code: -26, error_message: \\\"16: bad-txns-orchard-unknown-anchor\\\" }\"))" }`

update: im getting this error consistently for a specific wallet

**Comment by fluidvanadium** [comment]
another, simpler test is working

**Review by zancas — APPROVED** [review]

**Pull request merged**
