### PR TITLE
Update total z recipients

### PR DESCRIPTION
**Pull request by zancas**
Hi @juanky201271 the last commit in this PR will change the definition of:

`SendProgressCommand`

link in following comment.

### CODE REVIEW

**Comment by zancas** [comment]
https://github.com/zingolabs/zingolib/blob/ae6fe11e44405f2f772cca43d7aeac0fcf61bdd4/zingolib/src/commands.rs#L373

The underlying implementation now counts all shielded outputs to calculate the total (instead of just counting Sapling outputs).

**Review by fluidvanadium — DISMISSED** [review]
this looks good, but juanky should get a chance to look at it

**Comment by juanky201271** [comment]
> this looks good, but juanky should get a chance to look at it

Thanks @fluidvanadium ... I saw it and I believe the update of `total` here don't break anything in zingo-mobile...

**Comment by zancas** [comment]
OK, can someone please Approve this?

**Review by juanky201271 — APPROVED** [review]
sure....

**Review by juanky201271 — APPROVED** [review]
doing again...

**Pull request merged**
