### PR TITLE
remove ripemd160 in favor of SHA2 and cargo update

### PR DESCRIPTION
**Pull request by zancas**
Supersedes #1016

### CODE REVIEW

**Comment by zancas** [comment]
Easier to reimplement.

**Comment by zancas** [comment]
Shift to using the SHA256 digest provided by the Sha2 crate.

**Comment by fluidvanadium** [comment]
its cargo update that breaks ci

**Comment by zancas** [comment]
@Oscar-Pepper I think this is ready.

**Review by Oscar-Pepper — APPROVED** [review]

**Pull request merged**
