### PR TITLE
Hotfix

### LINKED ISSUE #826: Observed crash in IOS Xcode
google_play_panic

I hypothesize that this panic is caused by a panic in start_sync

https://github.com/zingolabs/zingolib/blob/f8c914a5894fd448d1b77556ad239c1f4f0ddad2/zingolib/src/lightclient.rs#L1388

### PR DESCRIPTION
**Pull request by AloeareV**
Fixes #826 (or at least, fixes the panic that we think is the cause of 826)

### CODE REVIEW

**Review by zancas — DISMISSED** [review]

**Review by zancas — CHANGES_REQUESTED** [review]
------------
     Summary [ 681.219s] 93 tests run: 92 passed (45 slow), 1 failed, 5 skipped
        FAIL [   2.658s] darkside-tests::network_interruption_tests interrupt_initial_tree_fetch
error: test run failed

**Comment by zancas** [comment]
Hmm..   I guess the previous fail was a flake...

```
cargo nextest run -p darkside-tests
   Compiling zingolib v0.2.0 (/home/nattyb/src/zingolabs/zingolibs/dev/zingolib)
   Compiling zingo-testutils v0.1.0 (/home/nattyb/src/zingolabs/zingolibs/dev/zingo-testutils)
   Compiling darkside-tests v0.1.0 (/home/nattyb/src/zingolabs/zingolibs/dev/darkside-tests)
    Finished test [optimized] target(s) in 38.93s
    Starting 14 tests across 5 binaries (2 skipped)
        PASS [   0.005s] darkside-tests constants::test::abandon_to_darkside_orch_10_000_000_zat
        PASS [   0.005s] darkside-tests constants::test::abandon_to_darkside_sap_10_000_000_zat
        PASS [   0.005s] darkside-tests::advanced_reorg_tests test_read_tree_state_from_file
        PASS [   0.006s] darkside-tests::advanced_reorg_tests test_read_block_dataset
        PASS [   2.356s] darkside-tests::network_interruption_tests interrupt_initial_tree_fetch
        PASS [   2.360s] darkside-tests::tests simple_sync
        PASS [   2.458s] darkside-tests::advanced_reorg_tests reorg_changes_incoming_tx_height
        PASS [   2.511s] darkside-tests::advanced_reorg_tests reorg_expires_incoming_tx
        PASS [   2.557s] darkside-tests::advanced_reorg_tests reorg_changes_incoming_tx_index
        PASS [   6.421s] darkside-tests::tests reorg_away_receipt
        PASS [   6.443s] darkside-tests::advanced_reorg_tests reorg_expires_outgoing_tx_height
        PASS [   6.902s] darkside-tests::advanced_reorg_tests reorg_changes_outgoing_tx_height
        PASS [   7.132s] darkside-tests::advanced_reorg_tests reorg_changes_outgoing_tx_index
        PASS [  13.426s] darkside-tests::tests sent_transaction_reorged_into_mempool
------------
     Summary [  13.429s] 14 tests run: 14 passed, 2 skipped
```

**Review by zancas — DISMISSED** [review]
The observed test fail, did not recur.

**Review by zancas — DISMISSED** [review]

**Comment by zancas** [comment]
We don't yet have functional network-interrupt tests in CI.  I have feature gated the test that was added to detect and fix this bug.

**Review by zancas — DISMISSED** [review]

**Review by zancas — DISMISSED** [review]

**Review by zancas — DISMISSED** [review]

**Comment by fluidvanadium** [comment]
hey hold your horses! im about to run these on my box. did you do the same?

**Comment by fluidvanadium** [comment]
why is it flaky?

**Comment by zancas** [comment]
Well, the feature gate didn't work with "cargo nextest run --archive-file", so I have reverted to `ignore`.

**Review by fluidvanadium — APPROVED** [review]
it proves the panic is fixed. i ran it 100 times locally with no failures. 
great!

**Review by zancas — APPROVED** [review]

**Pull request merged**
