### PR TITLE
Mini dep updates 3: Update Network Stack

### PR DESCRIPTION
**Pull request by fluidvanadium**

### CODE REVIEW

**Comment by zancas** [comment]
It seems likely to me that the dependency version conflict currently blocking CI would be resolved by depending on `zip339`.

**Comment by fluidvanadium** [comment]
> It seems likely to me that the dependency version conflict currently blocking CI would be resolved by depending on `zip339`.

zcash_primitives::...::zip339 which used to be a reexport of bip0039 no longer exists

**Comment by fluidvanadium** [comment]
force push reverted Cargo.lock accidental update

**Comment by fluidvanadium** [comment]
reopen

**Comment by fluidvanadium** [comment]
reopen and comment

**Pull request closed without merging**
