### PR TITLE
Rebroadcast Until Confirmed

### PR DESCRIPTION
**Pull request by fluidvanadium**
this is a relatively crude fix. however. it will likely fix the 'disappearing' (never confirming) transaction bug.

this may fix a hot test flake. furthermore, im setting up (blocked on #1478 ) a darkside script to prove it

### CODE REVIEW

**Review by zancas — CHANGES_REQUESTED** [review]
This looks great so far.   How hard will it be to add a test?

**Comment by fluidvanadium** [comment]
update: darkside test is providing difficulty with TxIds

**Review by fluidvanadium — COMMENTED** [review]
as discussed in meeting right now, should we merge and send to production tests?

**Comment by zancas** [comment]
I see that this test flakes on this code:

```
        PASS [ 343.896s] libtonode-tests::concrete slow::witness_clearing
------------
     Summary [1169.755s] 332 tests run: 331 passed (108 slow), 1 failed, 31 skipped
        FAIL [  91.938s] libtonode-tests::chain_generics chain_generics::simpool_zero_value_sapling_to_sapling
error: test run failed
1731615757 || shofth nattyb rebroadcast_when_evicted[ ]
REDACTED/rebroadcast_when_evicted RC: 100 $
git show -s
commit 077df24ad6de3b533e3778951c270362fa60162b (HEAD -> rebroadcast_when_evicted, zingolabs/dev, zingolabs/HEAD, dev)
Merge: 40771dd98 4a37b48af
Author: Za Wilcox <zancas@zingolabs.org>
Date:   Thu Nov 14 12:14:10 2024 -0700

    Merge pull request #1514 from zancas/cargo_update

    cargo update
    ```

Is it possible that this is a **new** flake?

**Review by zancas — APPROVED** [review]

**Pull request merged**
