### PR TITLE
Linking zingo-mobile to CI

### PR DESCRIPTION
**Pull request by Oscar-Pepper**

### CODE REVIEW

**Comment by AloeareV** [comment]
Is this still draft?

**Comment by Oscar-Pepper** [comment]
> Is this still draft?

yes, i am adding a check right now and will also try a commit with a broken zingolib to test for failure.
i also wanted to ask your opinions on containing the zingo-mobile build within the zingolib CI and not triggering zingo-mobile CI as discussed. this seemed like a simpler and maybe more flexible solution and we can still link the actions from the zingo-mobile CI.yml if the same workflow is a req

**Comment by zancas** [comment]
Heh...  `smasher`...

**Review by zancas — APPROVED** [review]
This is fantastic, and given that there's no effective test of zingolib code in the zingo-mobile Jest tests, elegant.

**Pull request merged**
