### PR TITLE
Make metadata underflow a clearer and more insistent error

### PR DESCRIPTION
**Pull request by AloeareV**

### CODE REVIEW

**Comment by AloeareV** [comment]
Note: Zingo-mobile and Zingo-PC may be relying on txsummaries being infallible, and now it can fail. This will need to be accounted for.

**Comment by juanky201271** [comment]
> Note: Zingo-mobile and Zingo-PC may be relying on txsummaries being infallible, and now it can fail. This will need to be accounted for.

I can see this error affect to several commands:
- summaries
- value_to_address
- sends_to_address
- memobytes_to_address

@AloeareV is that right?

**Comment by AloeareV** [comment]
> > Note: Zingo-mobile and Zingo-PC may be relying on txsummaries being infallible, and now it can fail. This will need to be accounted for.
> 
> I can see this error affect to several commands:
> 
> * summaries
> * value_to_address
> * sends_to_address
> * memobytes_to_address
> 
> @AloeareV is that right?

Yep, that should be the lot of it

**Comment by AloeareV** [comment]
Closing as unplanned.

**Pull request closed without merging**
