### PR TITLE
let people know where the wallet is, on collision

### PR DESCRIPTION
**Pull request by zancas**

### CODE REVIEW

**Comment by fluidvanadium** [comment]
> # [Codecov](https://codecov.io/gh/zingolabs/zingolib/pull/259?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=zingolabs) Report
> Base: **58.85**% // Head: **58.88**% // Increases project coverage by **`+0.03%`** tada
> 
> > Coverage data is based on head [(`7bd31d0`)](https://codecov.io/gh/zingolabs/zingolib/pull/259?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=zingolabs) compared to base [(`d23559d`)](https://codecov.io/gh/zingolabs/zingolib/commit/d23559d22f341002440c0dc9acffc292bf110438?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=zingolabs).
> > Patch coverage: 100.00% of modified lines in pull request are covered.
> 
> mega This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=zingolabs)
> 
> Additional details and impacted files
> [umbrella View full report at Codecov](https://codecov.io/gh/zingolabs/zingolib/pull/259?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=zingolabs). loudspeaker Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=zingolabs).

this is a good idea

**Comment by fluidvanadium** [comment]
see https://github.com/zingolabs/zingolib/pull/260#issuecomment-1447281195

**Comment by fluidvanadium** [comment]
This is useful! It makes the situation of loading a new wallet with zingo-cli easier, because now there's no struggle about finding the existing wallet.

One day, managing that existing wallet file could be a function of zingo-cli. This is a good glance in that direction.

**Comment by zancas** [comment]
Hi @fluidvanadium this PR staled, so I went through the process of rebasing it, fixing merge conflicts and re-pushing it.   Can you take a look?

**Pull request merged**
