### PR TITLE
Dev funded orchard with 3 txs mobileclient

### PR DESCRIPTION
**Pull request by zancas**
This is the exact same as @juanky201271 's PR but with one more commit.

### CODE REVIEW

**Comment by juanky201271** [comment]
Obviously, I have no idea that I was doing... but I was trying to follow a exists pattern: https://github.com/zingolabs/zingolib/blob/b5e50a4c72eb9f1ee6333549736085d2ad956fbb/zingo-testutils/src/lib.rs#L650

This is important too: https://github.com/zingolabs/zingo-mobile/pull/528

The idea is: I need to create a new scenario in `zingolib` (zingo-testutils) to be able to test a wallet with 3 transacciones:
- sent to another wallet.
- received from another wallet.
- Sent to Self.

The existent pattern is a funded wallet with 1 transaction (Received), and I copy this & add two more transactions. But because of my lack of knowledge about regtest & regchest & zingolib & rust... maybe I create a `RUST Frankenstein`, I don't know.

Said that, I need help to finish this scenario... I guess.

**Comment by zancas** [comment]
Oh..  I see.   Well I think you're mostly right, but this is a great thing for @Oscar-Pepper to review.  The code you wrote fulfills most of the conditions you were trying to fulfill, but it lacked a few "expert knowledge" bits that I think only @AloeareV @dannasessha and I have ever used before.   I'd like for @Oscar-Pepper and @fluidvanadium to check those comments, because that should help get them familiar with the test framework.

**Comment by Oscar-Pepper** [comment]
closed for #527

**Comment by zancas** [comment]
Hi @Oscar-Pepper and @juanky201271 I notices that this version didn't land, but I think that those comments are a super useful reference for people learning the test framework.  Is there a way to preserve them?   I think there's a lot of value there.

**Comment by juanky201271** [comment]
I can transfer them to the new implementation merged... @zancas

**Pull request closed without merging**
