### PR TITLE
Test data crate

### PR DESCRIPTION
**Pull request by zancas**
We are about to write a ton of unit-tests.   Where should the test-vectors live?

We want:

  * a single source of truth
  * ubiquitous access, including to independent projects
  * to manage data as native Rust types where feasible
  * to not run afoul of circular dependencies if we use a cratification strategy

The `zingo-testdata` crate is intended to support these requirements.
My intention is to re-export `zingo-testdata` from `zingolib` which will plausibly be the only crate that depends on it directly, as a dev-dependency.

It turns out that an optional dependency worked:

`zingo-testdata = { path = "../zingo-testdata", optional = true }`

Hopefully we can now chuck _ALL_ the test data in one spot.

I have not tried to be comprehensive grabbing all data sources..   whenever folks notice test data from outside `zingo-testdata` maybe they can just migrate it.

### CODE REVIEW

**Review by fluidvanadium — DISMISSED** [review]
when i run find -name chainstate, i see 4 similar directories in 3 different crates. is this intented organization?

why are testutils and testdata different crates. should one depend on the other?

**Comment by zancas** [comment]
This is the result of running find -name chainstate on dev:

```
find -name chainstate
./zingocli/regtest/data/zcashd/regtest/chainstate
./zingo-testutils/data/old_wallet_reorg_test_wallet/zcashd/regtest/chainstate
./zingo-testutils/regtest/data/chain_cache/blocks_1153/zcashd/regtest/chainstate
./zingo-testutils/regtest/data/regtestvectors/regtest/chainstate
```

So, I don't think this is ideal, but it's not a regression.   I will see about removing some of those.

**Comment by zancas** [comment]
By launching `zcashd` with a `zcash.conf` that contained `regtest=1`, while running `watch tree` in a another terminal, where the PWD of that terminal was the location of the `zcash.conf` file, I was able to observe the appearance of this directory structure:

```
Every 2.0s: tree                                                                                          shofth: Wed Dec 13 13:31:19 2023

.
├── regtest
│   ├── banlist.dat
│   ├── blocks
│   │   ├── blk00000.dat
│   │   ├── index
│   │   │   ├── 000003.log
│   │   │   ├── CURRENT
│   │   │   ├── LOCK
│   │   │   ├── LOG
│   │   │   └── MANIFEST-000002
│   │   └── rev00000.dat
│   ├── chainstate
│   │   ├── 000003.log
│   │   ├── CURRENT
│   │   ├── LOCK
│   │   ├── LOG
│   │   └── MANIFEST-000002
│   ├── database
│   │   └── log.0000000001
│   ├── db.log
│   ├── debug.log
│   ├── peers.dat
│   ├── wallet.dat
│   └── zcashd.pid
└── zcash.conf

6 directories, 20 files
```

I encourage folks to try this for themselves to appreciate the origin of these key files.

So at least some of the files your are seeing are *products* of zcashd test runs...   where this PR is concerned with unifying the input data.

I wholeheartedly agree that someone needs to unify the binaries and their results someone...   I have a plan...

**Comment by zancas** [comment]
@fluidvanadium I'd like to propose that landing this PR (or a modification of it) is the right move for upgrading our unit-(and other)-test capabilities.

**Comment by zancas** [comment]
@fluidvanadium hang on..  I am changing "data" to "testvectors" to make the definition more explicit.

**Comment by zancas** [comment]
Hey folks, by changing `data` to `vecctor` I hope I have clarified what _kind_ of contents we should put in this crate!

**Comment by zancas** [comment]
@fluidvanadium this PR is blocked on your review.

**Comment by fluidvanadium** [comment]
> @fluidvanadium this PR is blocked on your review.

1 hr sry

**Review by fluidvanadium — COMMENTED** [review]
i see that testutils now depends upon test flag zingolib which depends upon testvectors. alirght

approved pending local test success

**Comment by fluidvanadium** [comment]
> This is the result of running find -name chainstate on dev:
> 
> ```
> find -name chainstate
> ./zingocli/regtest/data/zcashd/regtest/chainstate
> ./zingo-testutils/data/old_wallet_reorg_test_wallet/zcashd/regtest/chainstate
> ./zingo-testutils/regtest/data/chain_cache/blocks_1153/zcashd/regtest/chainstate
> ./zingo-testutils/regtest/data/regtestvectors/regtest/chainstate
> ```
> 
> So, I don't think this is ideal, but it's not a regression. I will see about removing some of those.

i see that you didnt touch z-tu/regtest but moved z-tu/data.... alright. closing ChangeRequest

**Comment by fluidvanadium** [comment]
im getting integrations::load_old_wallet_at_reorged_height hangs locally....

**Review by fluidvanadium — APPROVED** [review]
this is a net increase in organization and i approve

**Pull request merged**
