### PR TITLE
added tests to reusable workflow and added all test to nightly ci

### PR DESCRIPTION
**Pull request by Oscar-Pepper**

### CODE REVIEW

**Review by juanky201271 — APPROVED** [review]
nice work.

**Review by zancas — APPROVED** [review]
Nice!

**Comment by zancas** [comment]
I wonder which the partitions are taking so long?  They should be fast.

**Review by zancas — DISMISSED** [review]
This is blocked on required jobs never returning statuses.    Can we move artifact construction/caching into nightly?

**Comment by Oscar-Pepper** [comment]
> This is blocked on required jobs never returning statuses. Can we move artifact construction/caching into nightly?

both ci and ci-nightly call test.yaml which includes the artifact construction , caching and testing. they take cargo nextest flags as an argument so we can filter tests differently when calling the test.yaml workflow. there is nothing wrong with the PR, we just need to update branch protection. i cant do that right now as i am still in process of replacing my phone so cant authorise it

**Pull request merged**
