### PR TITLE
Add devcontainer.json

### PR DESCRIPTION
**Pull request by AArnott**
This ensures that VS Code or GitHub Codespaces can automatically create an environment where `cargo build` and `cargo test` work.

## Devcontainer (on its own)

VS Code supports these natively. So long as you have Docker running, it'll create a container and map the git repo you already have into it if you run the "Reopen in devcontainer" command. Then you'll have all the tools necessary to build and test this repo, independent of what you may (not) have available on your regular dev machine.

## Codespaces

Codespaces leverage the devcontainer.json but adds value by hosting the container in the cloud for you. [Learn more about GitHub Codespaces](https://docs.github.com/en/codespaces/developing-in-codespaces/developing-in-a-codespace).

This root repo should consider [setting up a prebuild](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/configuring-prebuilds) of the Codespace to cache the docker image creation to make Codespace creation take just seconds.

For those using it, GitHub personal accounts can use Codespace VMs for free, to a point. [Learn details here](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces).
Note also that Codespaces VMs will sign your commits only if you have the repo set as a 'trusted' repo in your GitHub personal account settings.

You can see a sample of how Codespaces works by visiting [the source branch of this PR](https://github.com/nerdcash/zingolib/tree/devcontainer) and clicking the "<> Code" button:

image

Or use the `...` button to configure the size of the Codespace VM. Give yourself a 16 core machine and see just how fast `cargo build` can go!

### CODE REVIEW

**Comment by AloeareV** [comment]
This looks straight-forward, but I know very little about VSCode/devcontainers. @juanky201271 as far as I know you're the only one of us who's used tools along the lines of VSCode...if you have a couple minutes to sanity-check this I'd appreciate it!

**Comment by juanky201271** [comment]
Maybe it's my local configuration, but when I try to `open folder in container` I got this error: 
@AArnott

[2023-09-08T17:45:58.469Z] 
[+] Building 1.0s (6/6) FINISHED
 => [internal] load build definition from Dockerfile-with-features         0.0s
 => => transferring dockerfile: 864B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/zingodevops/ci-build:001        0.5s
 => [dev_container_auto_added_stage_label 1/3] FROM docker.io/zingodevops  0.0s
 => CACHED [dev_container_auto_added_stage_label 2/3] RUN apt-get update   0.0s
 => ERROR [dev_container_auto_added_stage_label 3/3] RUN ln -s /usr/bin/l  0.5s
------
 > [dev_container_auto_added_stage_label 3/3] RUN ln -s /usr/bin/lightwalletd /u
sr/bin/zcashd /usr/bin/zcash-cli ./zingocli/regtest/bin/:
#0 0.456 ln: target './zingocli/regtest/bin/': No such file or directory
------
error: failed to solve: executor failed running [/bin/sh -c ln -s /usr/bin/light
walletd /usr/bin/zcashd /usr/bin/zcash-cli ./zingocli/regtest/bin/]: exit code:

**Comment by AArnott** [comment]
@juanky201271 Thanks for testing. The relative paths in the Dockerfile work in a Codespaces container but not a local container I guess. Let me look more into this...

**Comment by AArnott** [comment]
Ok, for me it works both in VS Code local dev containers as well as Codespaces.

**Review by juanky201271 — APPROVED** [review]
It's working with VS in local... Great!

**Pull request merged**
