### PR TITLE
Invoke chain generics cleanly

### PR DESCRIPTION
**Pull request by zancas**
Builds on #1165

### CODE REVIEW

**Review by fluidvanadium — DISMISSED** [review]

**Review by fluidvanadium — DISMISSED** [review]
i love this reorganization! thank you

**Review by fluidvanadium — COMMENTED** [review]
oh, it may be a little confusing if they arent tested in the same order the fixtures are defined

**Comment by zancas** [comment]
> oh, it may be a little confusing if they arent tested in the same order the fixtures are defined

I will fix this in a subsequent PR.

**Review by fluidvanadium — APPROVED** [review]

**Comment by zancas** [comment]
Local tests pass.

**Pull request merged**
