### PR TITLE
Dry build rs

### PR DESCRIPTION
**Pull request by zancas**

### CODE REVIEW

**Comment by zancas** [comment]
Hi @fluidvanadium can you review this code?

**Comment by juanky201271** [comment]
@zancas dis you this error: https://github.com/zingolabs/zingolib/actions/runs/6045572683/job/16405837116?pr=458#step:7:29

**Review by fluidvanadium — APPROVED** [review]
this may be an organizational improvement

**Comment by zancas** [comment]
> @zancas did you this error: https://github.com/zingolabs/zingolib/actions/runs/6045572683/job/16405837116?pr=458#step:7:29

Yeah..  I think that this is because I forgot to commit the new crate.

**Review by fluidvanadium — APPROVED** [review]

**Pull request merged**
