### PR TITLE
create_on_data_dir is simply a public fn in zingolib

### LINKED ISSUE #21: Add back critical 'create' function needed by zingo-mobile
See here: 

https://github.com/zingolabs/zingo-mobile/blob/8ffe05eaacd97c843ff2caff04a31b3e3e1a6394/rust/lib/src/lib.rs#L26

### PR DESCRIPTION
**Pull request by zancas**
Fixes #21

Note the refactor of `ZingoConfig` will require refactor in mobile.. which I am looking into now.

### CODE REVIEW

**Comment by zancas** [comment]
I am delaying that refactor.   There're changes on dev in zingolib, unrelated to mving the config that effect mobile.  This should land as is.

**Comment by zancas** [comment]
This has been open for 10 days.

**Comment by dannasessha** [comment]
ACK, sorry for the delay.

**Comment by dannasessha** [comment]
Looks good! I am going to test locally but plan to merge shortly!

**Review by dannasessha — APPROVED** [review]
Seems good, thank you for your patience!

**Pull request merged**
