### PR TITLE
reduce batch size by 10x

### PR DESCRIPTION
**Pull request by zancas**
We need to discuss this before letting it integrate into mobile.

### CODE REVIEW

**Comment by zancas** [comment]
How can we safely test this?

**Comment by AloeareV** [comment]
> How can we safely test this?

Right now, we have no tests that involve large numbers of blocks... Generating blocks is computationally expensive, so I don't think we want to tell regtest to generate thousands of blocks during a test run. I think we want to generate a large blockchain (ideally several thousand blocks), with some sends back and forth, and save it as a test vector somewhere. That way, we can spend a long time generating it once, and then we can have tests that rescan it.

**Comment by zancas** [comment]
Great answer, but in the short term I was thinking of a manual test!

**Review by juanky201271 — APPROVED** [review]
Well, I think this change It's pretty straightforward... and we have to test it ASAP.

**Pull request merged**
